1.20.1 not use net.minecraftforge.bootstrap.ForgeBootstrap
kettingpowered/kettinglauncher pull request #12
Opened 2024-01-23 19:06 UTC by TonimatasDEV

Okey, now is ready

2024-01-23 19:11 UTC, C0D3-M4513R requested changes

2024-01-23 19:11 UTC, C0D3-M4513R commented on src/main/java/org/kettingpowered/launcher/KettingLauncher.java
> +        Class.forName(Bundled_McVersion.equals("1.20.1") ? "cpw.mods.bootstraplauncher.BootstrapLauncher" : "net.minecraftforge.bootstrap.ForgeBootstrap", true, KettingLauncher.class.getClassLoader()
Bundled_McVersion is only set when bundled. Will cause a NPE

2024-01-23 19:11 UTC, C0D3-M4513R commented on src/main/java/org/kettingpowered/launcher/KettingLauncher.java
> +        Class.forName(Bundled_McVersion.equals("1.20.1") ? "cpw.mods.bootstraplauncher.BootstrapLauncher" : "net.minecraftforge.bootstrap.ForgeBootstrap", true, KettingLauncher.class.getClassLoader()
Bundled_McVersion is only set when bundled. Will break in production.

2024-01-23 19:12 UTC, C0D3-M4513R commented
Also why change the way minecraft launches? it works just fine rn?

2024-01-23 19:13 UTC, TonimatasDEV commented
> Also why change the way minecraft launches? it works just fine rn?

It works but, mods need 1.20.1 libraries

2024-01-23 19:14 UTC, C0D3-M4513R commented
no mod should access 1.20.1 bootstrapper honestly.

2024-01-23 19:14 UTC, C0D3-M4513R commented
oh ffs. okay.

2024-01-23 19:16 UTC, C0D3-M4513R commented
Just replace `Bundled_McVersion` with `KettingConstants.MINECRAFT_VERSION`?

2024-01-23 19:20 UTC, TonimatasDEV commented
Now?

2024-01-23 19:21 UTC, C0D3-M4513R approved these changes

2024-01-23 19:22 UTC, C0D3-M4513R commented
Still unsure how we should go about the update tbh.
We'll see when the other pr is ready.

2024-01-23 19:26 UTC, C0D3-M4513R commented
I might rewrite this still. Something with the update doesn't sit right with me.
Maybe a combination of both ways.

2024-01-23 20:10 UTC, JustRed23 approved these changes

2024-01-25 14:06 UTC, C0D3-M4513R commented
We are working on `dev` for making cpw work.

2024-01-25 14:06 UTC, closed without merging