Now the processors works fine
kettingpowered/kettinglauncher pull request #27
Opened 2024-04-08 20:14 UTC by TonimatasDEV

2024-04-08 20:33 UTC, C0D3-M4513R requested changes
Red moved the switch statements into kettingcommon, because it is cleaner

2024-04-08 20:33 UTC, C0D3-M4513R commented on src/main/java/org/kettingpowered/launcher/Patcher.java
> +        }
Move to kettingcommon Type enum, just like the rest

2024-04-08 20:33 UTC, C0D3-M4513R commented on src/main/java/org/kettingpowered/launcher/Patcher.java
> +        }
Move to kettingcommon Type enum, just like the rest

2024-04-08 20:33 UTC, C0D3-M4513R commented on src/main/java/org/kettingpowered/launcher/Main.java
> +                            "2.0.17", // We need to get it
You could parse the library file for neoforge for this.

2024-04-08 20:33 UTC, C0D3-M4513R commented on src/main/java/org/kettingpowered/launcher/Main.java
> +                            "org.kettingpowered.server",
Todo: Does this cause a namespace collision with forge?

2024-04-08 20:42 UTC, JustRed23 commented on src/main/java/org/kettingpowered/launcher/Main.java
> +                            "org.kettingpowered.server",
neoforge.group is not valid, its not even a valid argument anymore, the whole group thing is only forge specific, so neoforge.group=org.kettingpowered.server can be safely removed

2024-04-08 21:24 UTC, TonimatasDEV commented
Idk why now kettingcommon give me some problems. If we can fix it for me.

2024-04-09 07:59 UTC, C0D3-M4513R commented
kettinglauncher just has problems with pulling files from your local maven repository.
You need to copy&paste the file manually. Otherwise it will not be copied correctly.

2024-04-09 09:38 UTC, JustRed23 commented
> kettinglauncher just has problems with pulling files from your local maven repository. You need to copy&paste the file manually. Otherwise it will not be copied correctly.

could we make it that when the version is detected as dev-env, that it can also pull from the local m2 repo?

2024-04-09 15:25 UTC, TonimatasDEV commented
For this work we need https://github.com/kettingpowered/kettingcommon/pull/4

2024-04-09 15:42 UTC, C0D3-M4513R requested changes
There will be issues when running kettinglauncher non-bundeled.

2024-04-09 15:42 UTC, C0D3-M4513R commented on src/main/java/org/kettingpowered/launcher/Main.java
> +    public static String NEOFORGE_FML_VERSION = "null";
This will only ever be properly set in a bundled scenario.
This also needs to work in a non-bundled scenario, from looking at the neoforge library list.

2024-04-09 18:20 UTC, TonimatasDEV commented
Done. For work need https://github.com/kettingpowered/kettingcommon/pull/4

2024-04-09 22:30 UTC, C0D3-M4513R requested changes
Sorry, that i keep finding shit.
This is most certainly incorrect though.

2024-04-09 22:30 UTC, C0D3-M4513R commented on src/main/java/org/kettingpowered/launcher/Patcher.java
> +        tokens.put("{PATCHED}", KettingConstants.TYPE.installJsonOrThrow().getAbsolutePath());
?

2024-04-09 22:37 UTC, TonimatasDEV commented on src/main/java/org/kettingpowered/launcher/Patcher.java
> +        tokens.put("{PATCHED}", KettingConstants.TYPE.installJsonOrThrow().getAbsolutePath());
Ups

2024-04-09 22:46 UTC, TonimatasDEV commented
> Sorry, that i keep finding shit. This is most certainly incorrect though.

Almost all of them are silly mistakes I make, I think I should program more concentrated.

2024-04-10 08:04 UTC, C0D3-M4513R approved these changes

2024-04-10 08:05 UTC, merged